name: az-deploy-n-test
on:
  push:
    branches:
      - 'main'
    paths:
      - '!schemas/**'
      - '**.bicep'
      - '**.jsonc'
      - '**.json'
      - '.github/ci.cmake'
      - '.github/workflows/az-deploy-n-test.yaml'
      - '.github/workflows/az-deploy.yaml'
      - '.github/workflows/az-deploy-test.yaml'
  workflow_dispatch:
    inputs:
      location:
        type: string
        description: 'Deployment location'
        required: true
jobs:
  deploy-n-test-matrix:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        config: ['DEFAULT', 'azfinsim-linux', 'azfinsim-windows']
    uses: ./.github/workflows/az-deploy.yaml
    with:
      location: ${{ github.event.inputs.location || 'eastus2' }}
      resource_group_name: 'sbatch-ci-${{ github.run_id }}-${{ matrix.config }}'
      enable_application_containers: true
      enable_application_packages: false
      config: ${{ matrix.config }}
    secrets: inherit
