name: ci-deploy-n-test
on:
  push:
    branches:
      - 'main'
    paths:
      - '!schemas/**'
      - '**.bicep'
      - '**.jsonc'
      - '**.json'
      - '**.ps1'
      - tests/**
      - '.github/ci/*.cmake'
      - '.github/workflows/ci-deploy-n-test.yaml'
      - '.github/workflows/az-deploy.yaml'
      - '.github/workflows/az-deploy-n-test-hub-n-spoke.yaml'
  workflow_dispatch:
    inputs:
      location:
        type: string
        description: 'Deployment location'
        required: true
concurrency: ${{ github.workflow }}-${{ github.event.inputs.location || 'eastus2' }}
jobs:
  deploy-n-test-matrix:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        test_suite: ['minimal', 'azfinsim-default', 'azfinsim-linux', 'azfinsim-windows']
    uses: ./.github/workflows/az-deploy.yaml
    with:
      test_suite: ${{ matrix.test_suite }}
      location: ${{ github.event.inputs.location || 'eastus2' }}
      resource_group_name: 'github-ci-${{ matrix.test_suite }}-${{ github.run_id }}'
    secrets: inherit
  deploy-n-test-secured-batch:
    needs: deploy-n-test-matrix
    uses: ./.github/workflows/az-deploy-n-test-hub-n-spoke.yaml
    with:
      location: ${{ github.event.inputs.location || 'eastus2' }}
      prefix: 'github-ci-sb'
    secrets: inherit
