name: ci-startup-script

on:
  push:
    branches:
      - 'main'
    paths:
      - 'examples/mpi-benchmarks/start_task.sh'
      - '.github/workflows/ci-startup-script.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'examples/mpi-benchmarks/start_task.sh'
      - '.github/workflows/ci-startup-script.yaml'

permissions:
  contents: write

jobs:
  'mpi-benchmarks':
    runs-on: ubuntu-latest
    container: redhat/ubi8:8.4
    steps:
    - name: checkout source
      uses: actions/checkout@v3
    - name: run 'examples/mpi-benchmarks/start_task.sh'
      run: bash ./examples/mpi-benchmarks/start_task.sh
    