name: ci-validate-configs

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.json'
      - '**.jsonc'
      - '**.bicep'
      - '.github/workflows/ci-validate.yaml'
  pull_request:
    branches:
      - 'main'
    paths:
      - '**.json'
      - '**.jsonc'
      - '**.bicep'
      - '.github/workflows/ci-validate.yaml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-22.04
    environment: azure
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: checkout source
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: validate bicep
      run: |
        az --version
        az bicep build --file $GITHUB_WORKSPACE/modules/infrastructure.bicep
        file $GITHUB_WORKSPACE/modules/infrastructure.json

    - name: validate examples bicep
      run: |
        find "$GITHUB_WORKSPACE/examples" -type f -name "deployment.bicep" | while read -r file; do
          az bicep build --file "$file"
        done
    # - name: Install dependencies
    #   run: |
    #     python3.8 -m pip install --upgrade pip
    #     python3.8 -m pip install ./cli
    # - name: validate config.template.jsonc
    #   run: |
    #     sb json strip -i $GITHUB_WORKSPACE/config/config.template.jsonc > $GITHUB_WORKSPACE/config/config.json
    #     jsonschema -i $GITHUB_WORKSPACE/config/config.json $GITHUB_WORKSPACE/schemas/config.schema.json
    # - name: validate hubConfig.template.jsonc
    #   run: |
    #     sb json strip -i $GITHUB_WORKSPACE/config/hubConfig.template.jsonc > $GITHUB_WORKSPACE/config/hubConfig.json
    #     jsonschema -i $GITHUB_WORKSPACE/config/hubConfig.json $GITHUB_WORKSPACE/schemas/hub.schema.json
